flags:
    text:
        integer-simple: false
packages:
- '.'
extra-deps:
    - mtl-2.2.1
    - network-2.6.3.3
    - stm-2.4.4.1
    - transformers-0.5.2.0
    - attoparsec-0.13.2.2
    - hashable-1.2.6.1
    - scientific-0.3.5.2
    - text-1.2.2.2
    - base-4.8.2.0
allow-newer: true
resolver: lts-10.4
